timezone: Europe/Warsaw
plugins:
  - jekyll-redirect-from
sass:
  style: compressed
collections:
  pages:
    output: true
  posts:
    permalink: /:name
  shop:
    permalink: /:name
    output: true
